### ISSUE TITLE
I'm a python programmer with some C and linux skills, how can a I help you in advancing desktopbsd?

### ISSUE THREAD

**Issue by auvipy** [desktopbsd/desktopbsd#68]

**Comment by pkgdemon** [comment]
Hi.  Thanks for reaching out.  The biggest thing that will pertain to you the most will be the creation of tools in M4.  I could really use the most help on this area.

https://github.com/desktopbsd/desktopbsd/milestones/DesktopBSD%202.0%20M4

With that said any of the open that show help wanted are up for grabs.

https://github.com/desktopbsd/desktopbsd/issues

If you come up with something to share, or need further guidance to get started please let us know.

**Comment by auvipy** [comment]
I question, is it possible to build desktopbsd onlinux distors? i use ubuntu

**Comment by pkgdemon** [comment]
It's not possible to build in the Ubuntu OS natively yet.  It might be possible to assemble and ISO in the future if pkg could be ported over to Linux.  You can definitely use Virtual Box, or KVM to install a FreeBSD current snapshot on top of Ubuntu, and begin building that way.  

This isn't official yet until it's done but here are the new build scripts that will be up on the DesktopBSD repo, and some instructions I have been working on.

https://github.com/pkgdemon/desktopbsd-livecd
https://docs.google.com/document/d/1ce_QHDpcSxK9fitqODYospqABGQnrcNHz6TpMSPldtM/edit?usp=sharing
http://www.desktopbsd.net/wiki/Development

It's all a work in progress though.  Not a whole lot to see yet other than the M1 image we release a month or so ago.

**Comment by pkgdemon** [comment]
These items have been moved to the main desktopbsd repo with further instructions as things are progressing.  If you have further questions please hop on our irc #DesktopBSD on FreeNode, or our forums.  I'm malco_2001 for both.
